version: "3.8"
services:
  db:
    image: mysql:8
    container_name: gas_station_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: gas_station
      MYSQL_USER: gasuser
      MYSQL_PASSWORD: gaspass
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
