module.exports = {
  other: ["Other"],

  kitchen: [
    "Guests Dinner/Lunch",
    "Guests Refreshments",
    "Daily Kitchen Expense",
    "Staff Food Allowance-Weekly",
    "Gas Cylinder Refilling",
    "External Mechanics/Labour Food Expenses",
    "Other",
  ],

  general: [
    "Bill-Internet",
    "Bill-Newspaper",
    "Bill-PTCL/WiFi",
    "Fake Currency Note Adjustment",
    "Fuel/CNG Asstt. Manager",
    "Fuel/CNG Manager",
    "Jehanzeb Khan Monthly Expenditure",
    "Khadim Hussain Kids School Fee",
    "KP Dir. of Labour (Weight & Measurement) Annual Fee",
    "Local Purchase & Repair-CCTV",
    "Local Purchase-General",
    "Local Purchase-Premises Fixtures",
    "Petty Cash",
    "Repair-Air Conditioner",
    "Repair-Canopy",
    "Repair-Office Furniture/Equipment",
    "Repair-Premises Structure & Fixtures",
    "Transport Intercity",
    "Transport Local",
    "Other",
    "Discount Armed Forces",
    "Prize Scheme Cash/Item Expenditure",
  ],

  generatordieselelubecompressor: [
    "Diesel-Generator",
    "Lubricant-Compressor",
    "Lubricant-Generator",
    "Other",
  ],

  salary: [
    "Balance Monthly Pay Roll",
    "Salary-Advance",
    "Salary-Monthly",
    "Shahzeb Khan-Allowance",
    "Other",
  ],

  premisesrent: [
    "Rent Premises-Janib Shah",
    "Rent Premises-Zareef",
    "Rent Premises-Zareef",
    "Other",
  ],

  pettycash: [],

  kgandjaws: [
    "Dry Ration",
    "Tandoor Roti",
    "Langar Cook Salary",
    "Loader Petrol/Lube",
    "Loader Repair",
    "Vegetables",
    "Other",
  ],

  loansgivenreturnedtostation: [
    "Loan Given by Papoo Khan",
    "Loan Given by Ejaz Khan",
    "Loan Given by Dr. Nasir Khan",
    "Loan Given by Nadeem Khan",
    "Loan Repaid to Papoo Khan",
    "Loan Repaid to Dr. Nasir Khan",
    "Loan Repaid to Ejaz Khan",
    "Loan Repaid to Nadeem Khan ",
    "Personal Loan Repaid by Papoo Khan",
    "Personal Loan Repaid by Dr. Nasir Khan",
    "Personal Loan Repaid by Ejaz Khan",
    "Personal Loan Repaid by Nadeem Khan",
    "Loan Returned by Employee",
    "Other",
  ],

  machineryrepair: [
    "Cooling Tower Chemical",
    "Local Purchase Spare Parts-compAir Compressor",
    "Local Purchase Spare Parts-Cooling Tower",
    "Local Purchase Spare Parts-Dispenser",
    "Local Purchase Spare Parts-Generator",
    "Repair CNG Compressor",
    "Repair CNG Compressor-CompAir",
    "Repair CNG Compressor-Morgan",
    "Repair Cooling Tower",
    "Repair Generator",
    "Repair Dispenser",
    "Repair Water Motor Cooling Tower",
    "Testing/Calibration of Dispenser Meter",
    "Testing/Calibration of Gas Meter",
    "Local Purchase Spare Parts-Morgan Compressor",
    "Other",
  ],

  loansexpenditurebyakeknknk: [
    "Joint Expenditure 4Bro",
    "Monthly Disbursement-Dr. Nasir Khan",
    "Monthly Disbursement-Ejaz Khan",
    "Monthly Disbursement-Nadeem Khan",
    "Monthly Disbursement-Papoo Khan",
    "Rent Premises-Bara Road LPG",
    "Rent Premises-Farhan Shagai LPG",
    "Rent Premises-Mansehra LPG",
    "Waqar Khan Profit Share",
    "F.K-Profit/Loss Share on CNG/LPG (3%/5%)",
    "S.U-Profit/Loss Share on CNG/LPG (1.5%/2.5%)",
    "Personal Loan-Papoo Khan",
    "Personal Loan-Dr. Nasir Khan",
    "Personal Loan-Ejaz Khan",
    "Personal Loan-Nadeem Khan",
    "Other",
  ],

  loansexpendituredisbthrucheque: [
    "Joint Expenditure 4Bro",
    "Monthly Disbursement-Dr. Nasir Khan",
    "Monthly Disbursement-Ejaz Khan",
    "Monthly Disbursement-Nadeem Khan",
    "Monthly Disbursement-Papoo Khan",
    "Rent Premises-Bara Road LPG",
    "Rent Premises-Farhan Shagai LPG",
    "Rent Premises-Mansehra LPG",
    "Waqar Khan Profit Share",
    "F.K-Profit/Loss Share on CNG/LPG (3%/5%)",
    "S.U-Profit/Loss Share on CNG/LPG (1.5%/2.5%)",
    "Personal Loan-Papoo Khan",
    "Personal Loan-Dr. Nasir Khan",
    "Personal Loan-Ejaz Khan",
    "Personal Loan-Nadeem Khan",
    "Other",
  ],

  otherrevenue: [
    "Rent Sakhi Car Wash",
    "Electricity Bill Sakhi Car Wash",
    "Rent Tuck Shop",
    "Electricity Bill Tuck Shop",
    "GO Monthly Rent",
    "Loan Returned by Employee",
    "Other",
  ],

  utilitybills: ["PESCO Bill", "SNGPL Bill", "Other"],

  expenditurethrucheque: ["other"],
};
